# This is the default and 'official' registry for the Centi package manager.
# It is a simple file hosted on GitHub, which contains a list of packages.
# To add your own packages to the registry, simply fork the repository, add your packages to the file, and submit a pull request.

# Registry Fields #
# [registry_name]
# version = "x.y.z" # REQUIRED: The version of the package, in semantic versioning format.
# description = "A short description of the package." # OPTIONAL: A short description of the package.
# url = "https://example.com/package" # REQUIRED: The URL where the package can be. Must be a direct link to a binary file (e.g. .exe, .bin, .sh, etc.) or a script file (e.g. .py, .js, etc.) that can be executed directly.

[hello]
version = "1.0.0"
description = "A simple package that prints 'Hello, World!'"
url = "https://raw.githubusercontent.com/tyydev1/hello/refs/heads/main/hello.sh"
